name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Pastikan ini v4
      - uses: actions/checkout@v4

      # Pastikan ini v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Setup & Build
        run: |
          # Otomatis buat folder jika lupa
          mkdir -p www
          if [ -f "index.html" ]; then mv index.html www/; fi
          
          cordova platform add android
          cordova build android --debug

      - name: Upload APK
        # Inilah yang paling sering menyebabkan error jika masih v3
        uses: actions/upload-artifact@v4
        with:
          name: Hasil-APK-Z-Learning
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
