name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Pastikan ini v4
      - uses: actions/checkout@v4

      # Pastikan ini v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Setup & Build
        run: |
          # Perintah untuk build
          cordova platform add android
          cordova build android --debug

      - name: Upload APK
        # Inilah yang paling penting diubah ke v4
        uses: actions/upload-artifact@v4
        with:
          name: Hasil-APK-BACA-Arham
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
