name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Accept Android Licenses
        # Langkah ini sangat penting agar tidak Exit Code 1
        run: yes | sdkmanager --licenses || true

      - name: Build Android
        run: |
          cordova telemetry off
          mkdir -p www
          # Menambahkan platform secara bersih
          cordova platform add android@12.0.0
          # Proses build debug
          cordova build android --debug --device
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Aplikasi-BACA-Arham-Sukses
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
