name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Accept Android Licenses
        # Perintah ini untuk mengatasi eror di detik ke-33 tadi
        run: yes | sdkmanager --licenses || true

      - name: Setup & Build
        run: |
          cordova telemetry off
          # Memastikan folder www ada
          mkdir -p www
          # Menambahkan platform dan build
          cordova platform add android@12.0.0
          cordova build android --debug --device

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Aplikasi-BACA-Arham-Sukses
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
