name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Cordova & Plugins
        run: |
          npm install -g cordova
          # Menambahkan plugin whitelist secara otomatis
          cordova plugin add cordova-plugin-whitelist || true

      - name: Setup & Build
        run: |
          mkdir -p www
          cordova platform add android@12.0.0 --non-interactive
          cordova build android --debug --device
        env:
          CI: true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BACA-APK-FINAL-SUKSES
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
