name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses || true

      - name: Setup & Build
        run: |
          # Mematikan pengumpulan data agar robot tidak bingung
          export CI=true
          # Pastikan folder www ada
          mkdir -p www
          # Tambah platform android versi stabil
          cordova platform add android@12.0.0 --non-interactive
          # Proses build akhir
          cordova build android --debug --device

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Hasil-APK-BACA-Final
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
